# Generated by Django 4.0 on 2022-02-07 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_by', models.CharField(max_length=255, null=True)),
                ('create_at', models.DateField(null=True)),
                ('create_from', models.CharField(max_length=255, null=True)),
                ('modified_by', models.CharField(max_length=255, null=True)),
                ('modified_at', models.DateField(null=True)),
                ('modified_from', models.CharField(max_length=255, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_by', models.CharField(max_length=255, null=True)),
                ('archived_at', models.DateField(null=True)),
                ('archived_from', models.CharField(max_length=255, null=True)),
                ('facility_name', models.CharField(max_length=100)),
                ('facility_image', models.ImageField(upload_to='facility/image')),
                ('facility_details', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
