# Generated by Django 4.0 on 2022-01-17 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=2)),
                ('roll', models.PositiveIntegerField()),
                ('section', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1)),
                ('admission_date', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Students.student')),
            ],
        ),
    ]
