# Generated by Django 4.0 on 2022-01-17 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0002_classinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardianInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=11)),
                ('NID_card', models.CharField(max_length=13)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('B+', 'B+'), ('A-', 'A-'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('none', 'none')], default='none', max_length=4)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Students.student')),
            ],
        ),
    ]
