# Generated by Django 4.0 on 2022-01-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0003_guardianinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='student/image'),
        ),
    ]
