# Generated by Django 4.0 on 2022-01-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0004_student_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='student/profile_pic'),
        ),
    ]
