# Generated by Django 4.0.1 on 2022-03-02 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0013_studentpost_user_alter_studentpost_post_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpost',
            name='post_picture',
            field=models.ImageField(blank=True, null=True, upload_to='student/post'),
        ),
    ]
