# Generated by Django 4.0 on 2022-01-17 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.CharField(max_length=100)),
                ('result', models.CharField(max_length=20)),
                ('On_a_scale_of', models.CharField(choices=[('GPA 5', 'GPA 5'), ('CGPA 4', 'CGPA 4'), ('Division', 'Division')], max_length=20)),
                ('institute', models.CharField(max_length=50)),
                ('board', models.CharField(blank=True, max_length=15, null=True)),
                ('passing_year', models.CharField(max_length=4)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Teachers.teacher')),
            ],
        ),
    ]
