# Generated by Django 4.0 on 2022-01-17 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0002_teachereducation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=50)),
                ('joining_date', models.DateField()),
                ('leaving_date', models.DateField()),
                ('job_detail', models.TextField(blank=True, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Teachers.teacher')),
            ],
        ),
    ]
