# Generated by Django 4.0 on 2022-01-18 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0003_teacherexperience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachereducation',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Teacher_Education', to='Teachers.teacher'),
        ),
        migrations.AlterField(
            model_name='teacherexperience',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Teacher_Experience', to='Teachers.teacher'),
        ),
    ]
