# Generated by Django 4.0 on 2022-01-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0003_guardianinfo'),
        ('Teachers', '0004_alter_teachereducation_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='student',
            field=models.ManyToManyField(blank=True, null=True, to='Students.Student'),
        ),
    ]
