# Generated by Django 4.0 on 2022-01-19 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0005_teacher_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='student',
        ),
    ]
