# Generated by Django 4.0 on 2022-01-26 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0006_remove_teacher_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='teacher/profile_pic'),
        ),
    ]
