# Generated by Django 4.0.1 on 2022-03-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0008_teacher_archived_at_teacher_archived_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='Position',
            field=models.CharField(blank=True, choices=[('Principal', 'Principal'), ('Senior Teacher', 'Senior Teacher'), ('Junior Teacher', 'Junior Teacher'), ('Part Time Teacher', 'Part Time Teacher')], max_length=20, null=True),
        ),
    ]
