# Generated by Django 4.0.1 on 2022-03-02 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Settings', '0002_alter_footerdata_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerdata',
            name='copyright_owner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
