# Generated by Django 4.0.1 on 2022-03-02 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Settings', '0003_footerdata_copyright_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerdata',
            name='copyright_owner',
            field=models.CharField(max_length=100),
        ),
    ]
