gender_choice = (("M", "Male"), ("F", "Female"), ("T", "Other"))
religion_choice = (("Islam", "Islam"), ("Hindu", "Hindu"), ("Christian", "Christian"), ("Buddha", "Buddha"))
blood_group_choice = (("A+", "A+"), ("B+", "B+"), ("A-", "A-"), ("B-", "B-"), ("AB+", "AB+"), ("AB-", "AB-"), ("none", "none"))
class_choice = (("1", "1"), ("2", "2"), ("3", "3"), ("4", "4"), ("5", "5"))
section_choice = (("A", "A"), ("B", "B"))
